branches:
  only:
  - master
language: python
python:
- 2.7
script:
- git config remote.origin.url | sed 's/^/https:\/\//g' 
- make github
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: J3w2nDb+SUXWtrIyKrfmpWZlouFNPRAijiCLIa64L/L8zdshQCJa+fvXrZR6Xb/sgIZkw6hYtaQiH2nXGh98KUAEOBAG7Bgc5lqv5uzt8+wCZoXWM2tQ3rrYgSgoQSr0Otdq4EoyBj4pBWPKa+uNZjKMbP97/Gvgr2cqi7CUERA=
  - secure: W7atJSXEk4hQST1gG712K4RhizzK1wjgkkBzCgKV7eYLbspPSnVJIBI3Yjc4CgkcMpzxY3Xm+xW8GBpq66Lu9+3po/jd13SADO/SM0pF82wh5+gl/NpzdrTkaAIs5I+W4/lUGz+/Inc9jWvtQSNy4JlpR0Z/yhjHndgvBczJd/U=
after_success:
- make publish
