branches:
  only:
  - master
language: python
python:
- 2.7
script:
- make github
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: "O4Z29lCmdznyRc/g36xhNje2Sa06O4pZs3Vw2XaBwPWzaBqkEI9ULpckuggclAyZWjPB1MM6BR2w59hsoyXyuOchcwJM4zyOY6YZctbwwmglgrUuPYb40bkoMc+Jh5Z0wqsnfcaEIrb5vbA+EsbX92mVWEivY1cC7Z7UksiSAjk="
